version: '3.8'

services:
  db:
    image: postgres:15
    container_name: medical_tests_db
    environment:
      POSTGRES_DB: medical_application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3891123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medical_tests_api
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:3891123@db:5432/medical_application
      SECRET_KEY: your-super-secret-key-change-this-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    build:
      context: ./frontend/frontend_project
      dockerfile: Dockerfile
    container_name: medical_tests_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://api:8000
      NEXT_TELEMETRY_DISABLED: 1
      LIGHTNINGCSS_NO_NATIVE: 1
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend/frontend_project:/app
    command: >
      sh -c "
        rm -rf .next/cache &&
        npm run dev"

volumes:
  postgres_data: