

services:
  db:
    image: postgres:15
    container_name: medical_tests_db
    environment:
      POSTGRES_DB: medical_application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3891123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medical_tests_api
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:3891123@db:5432/medical_application
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: medical_tests_frontend
  #   environment:
  #     NEXT_PUBLIC_API_URL: http://localhost:8000
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #     - /app/.next

volumes:
  postgres_data:
