"""Update question fields to use JSON type

Revision ID: 4d38510afd5e
Revises: 002
Create Date: 2025-08-09 15:35:28.007599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d38510afd5e'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    
    # Используем USING для преобразования VARCHAR в JSON
    op.execute("ALTER TABLE questions ALTER COLUMN options TYPE JSON USING options::json")
    op.execute("ALTER TABLE questions ALTER COLUMN correct_answers TYPE JSON USING correct_answers::json")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Используем USING для преобразования JSON в VARCHAR
    op.execute("ALTER TABLE questions ALTER COLUMN correct_answers TYPE VARCHAR USING correct_answers::text")
    op.execute("ALTER TABLE questions ALTER COLUMN options TYPE VARCHAR USING options::text")
    op.alter_column('questions', 'question_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
