"""НА ВСЯК

Revision ID: 612e3c0ef06c
Revises: cf70185a207c
Create Date: 2025-08-12 08:58:31.085464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612e3c0ef06c'
down_revision: Union[str, Sequence[str], None] = 'cf70185a207c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tests_test_id_key', 'tests', type_='unique')
    op.drop_column('tests', 'test_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('tests_test_id_key', 'tests', ['test_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
