"""add_test_id_field

Revision ID: 946b9c6f99bb
Revises: 4d38510afd5e
Create Date: 2025-08-10 07:15:14.482121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946b9c6f99bb'
down_revision: Union[str, Sequence[str], None] = '4d38510afd5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('test_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'tests', ['test_id'])
    op.drop_index('ix_users_email', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_constraint(None, 'tests', type_='unique')
    op.drop_column('tests', 'test_id')
    # ### end Alembic commands ###
