"""fix for reload test_id

Revision ID: cfbf0f4b7467
Revises: aca3e92c351a
Create Date: 2025-08-12 17:18:29.661930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfbf0f4b7467'
down_revision: Union[str, Sequence[str], None] = 'aca3e92c351a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('test_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'questions', 'tests', ['test_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'test_id')
    # ### end Alembic commands ###
