"""fix

Revision ID: f26e795e2a3a
Revises: 2a6ab763cb8c
Create Date: 2025-08-12 17:11:55.760978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26e795e2a3a'
down_revision: Union[str, Sequence[str], None] = '2a6ab763cb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_test_id_fkey', 'questions', type_='foreignkey')
    op.drop_column('questions', 'test_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('test_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('questions_test_id_fkey', 'questions', 'tests', ['test_id'], ['id'])
    # ### end Alembic commands ###
